Feature/qrscanner
the-kerfi-team/syski_client_android pull request #4
Opened 2019-02-17 20:02 UTC by dscurrey

Please test on one of your devices to confirm it's working before merging.

2019-02-17 20:04 UTC, dscurrey commented
![](https://github.trello.services/images/mini-trello-icon.png) [QR codes to view system information](https://trello.com/c/0lsmzA3z/2-qr-codes-to-view-system-information)

2019-02-17 22:22 UTC, Stedoss requested changes
Activity (camera) does not load on some devices. This ideally should be fixed before merging.

2019-02-22 07:39 UTC, JLScott1999 approved these changes

2019-02-22 10:16 UTC, Stedoss approved these changes

2019-02-22 10:16 UTC, merged